spring.application.name=demo
server.port=9000

# MongoDB Configuration
# Replace <username>, <password>, and <cluster-url> with your MongoDB Atlas details
spring.data.mongodb.uri=mongodb+srv://admin:mongoDBadmin@cluster1.xxgi15b.mongodb.net/expensodb?retryWrites=true&w=majority

# mongodb+srv://admin:<db_password>@cluster1.xxgi15b.mongodb.net/
